### ISSUE TITLE
RAP64 crash when you do this steps

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAEmus#15] opened 2018-11-08 00:32 UTC
Every time you opened the achievement set > editor > inspector in that order, the emulator crashes, this only happen when you loaded a rom, but is very strange a situation when you openned all this without a rom loaded before, so basically is every time

Also only happen when you recently open the emulator, does not happen if you open the set, editor and inspector properly before and you still don't close the emu.
To work properly you need to open the inspector first and after that open the set and the cheevo editor
Happened to me a lot of times, it's a bit annoying 🙄

Also when you are making cheevos on local, it duplicates all of them some times, I don't have the exact steps to trigger but happened to me like 3 or 4 times, in a moment you have 24 cheevos and later you have 48, all the same cheevos duplicated lol, this only happen when you have 25> cheevos on average

Also I don't have the exact steps for this too but when you crash rap64 > reopened, if the RA welcome text appeared with some lag, that mean the emu will automaticly reset (with no sound) in a couple mins. Only happen when you crashed the emu recently

**Comment by eldexterr** [comment] 2018-11-08 00:44
Here is a video:
https://goo.gl/1wMrPz
The thing about the Laggy RA welcome message happened to me at the end of the video too

**Comment by SyrianBallaS** [comment] 2018-11-08 04:56
I can confirm this happens on the prod version of RAProject64 but can't repoduce it with other emulators. I tried testing RAProject64 with a dev build of the integration (from my custom_deleters branch) and it didn't crash, but weird stuff still happened. Other emulators tested (just dropped the dll in there) were RANes, RASnes, and RAVBA. Prod and that dev one were used separately to see if there was a difference.

I think it'll get mostly resolved in the next Integration update (as far as crashing goes), there are some huge differences. Most likely a deadlock/memory leak. I still think there might be something wrong with RAProject64 itself because it doesn't always resume when you click the emulator window.

I tried showing a video as well but my computer sucks at recording/streaming. It did hang a little bit but resumed by itself or had to press "pause" to resume (really weird). Didn't lag either.

**Comment by Jamiras** [comment] 2018-11-08 15:19
The problem is a deadlock in the toolkit dll. The memory inspector is trying to fetch the code notes on "Main Thread", while the Badges list on the Achievement Editor is trying to populate itself on the "RAProject64.exe thread" via the "RA_HandleHttpResults" callback. The achievement editor is holding a lock on RAWeb::mutex, and trying to call `ComboBox_AddString`, which is waiting for the message loop on the main thread to process the message. However, the main thread is waiting for the `RAWeb::mutex` so it can queue fetching the badges list.

In your video, when it crashes, you can see the Badge dropdown is still blank. If you'd wait for it to populate before trying to open the memory inspector, the problem should not occur.

This is fixed in the latest DLL with the Http service rewrites. Requests are no longer queued. They're immediately dispatched to background threads. Without the queue, there's no attempt to lock, and the deadlock is avoided.

This doesn't happen in other emulators because the `RA_HandleHttpResults` method is called on the "Main Thread".

Regarding the laggy welcome message, that's most likely the result of populating the Badge list as well. That logic really should be moved (or eliminated entirely). It makes opening the Achievement Editor introduce an unnatural pause on every emulator. The dropdown should be replaced with a simple textbox. Most people upload new images, rather than select existing ones, and those that are selecting existing ones could just type in the ID.

In any case, I believe this to be a toolkit issue, and one that has been fixed.

I have not seen the duplicated local achievements. If you can find steps to reproduce, please create a new issue.

**Closed by Jamiras** 2018-11-08 15:19 UTC
