### ISSUE TITLE
Can't compile snes9x

### ISSUE THREAD

**Issue by DQ318** [RetroAchievements/RAEmus#17] opened 2018-11-15 17:59 UTC
I'm trying to compile the solution, more specifically snes9x, however, visual studio simply presents thousands of errors when compiling. I already have all the requirements installed and would like some help to get compile. Can someone guide me? Thank you

**Comment by DQ318** [comment] 2018-11-16 14:38
@Jamiras 
Hi man, Thanks for answering. I will try to explain what I did and what I have to error so far:

1 - I downloaded and installed VS 2017 on my Windows 7.
2 I installed the support for Windows XP for C ++ in my VS 2017.
3 - Download the RAEmus Master project by clicking on Clone or Download and then clicking Download ZIP.
4 - I unzipped and opened the file RASnes9x.sln in my VS 2017.
5 - When loading the project, I clicked the local debugger, win32 and, when compiling, several errors arise:

===== ERRORS =====
1> ------ Compilation started: Project: libpng, Configuration: LIB Release Win32 ------
2> ------ Compilation started: Project: zlib, Configuration: ReleaseWithoutAsm Win32 ------
1> 1 file (s) copied.
2> zlibstat.vcxproj -> D: \ Programs and Windows \ PROGRAMS \ 06 - Cpp \ RAEmus-master \ RAEmus-master \ RASnes9x \ zlib-1.2.8 \ contrib \ vstudio \ vc9 \ x86 \ ZlibStatRelease \ zlib.lib
1> libpng.vcxproj -> D: \ Programs and Windows \ PROGRAMS \ 06 - Cpp \ RAEmus-master \ RAEmus-master \ RASnes9x \ libpng \ projects \ visualc71 \. \ Win32_LIB_Release \ libpng.lib
3> ------ Compilation started: Project: RASnes9X, Configuration: Win32 Release ------
3> fatal: not a git repository (or any of the parent directories): .git
3> Not a git repository
3> To compare two paths outside a working tree:
3> usage: git diff [--no-index] <path>
3> Tag: (~ 9,3)
3> cpu.cpp
3> memmap.cpp
3> wsnes9x.cpp
3> CDirectDraw.cpp
D: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ win32 \ cdirectdraw.cpp (185): fatal error C1083: Unable to open file include: 'RA_Interface.h' : No such file or directory
D: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ memmap.cpp (180): fatal error C1083: Unable to open file include: 'RA_Interface.h': No such file or directory
3> RA_Implementation.cpp
3> RA_Interface.cpp
3> c1xx: fatal error C1083: Unable to open source file: '.. \ .. \ RA_Integration \ src \ RA_Interface.cpp': No such file or directory
D: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ win32 \ ra_implementation.cpp (2): fatal error C1083: Unable to open file include: 'RA_Interface.h' : No such file or directory
C4091: 'typedef': Ignored to the left of 'tagGPFIDL_FLAGS' when no variable is declared (compiling source file.) C: \ Program Files \ Microsoft \ wsnes9x.cpp)
(277): error C2061: syntax error: '_Filet' identifier (compiling source file): d: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ win32 \ _tfwopen.h wsnes9x.cpp)
(C: \ windows \ programs \ 06) - cpp \ raemus-master \ raemus-master \ rasnes9x \ win32 \ _tfwopen.h (277): error C2535: 'std :: u8nifstream :: u8nifstream (void)': member function already defined or declared (compiling source file wsnes9x.cpp)
D: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ win32 \ _tfwopen.h (257): note: see the 'std :: u8nifstream :: u8nifstream' statement ( compiling source file wsnes9x.cpp)
(278): error C2065: '_File': undeclared identifier (compiling source file wsnes9x (278): error C2065: '_File': unrecognized identifier (compiling source file wsnes9x .cpp)
D: \ programs and windows \ programs \ 06 - cpp \ raemus-master \ raemus-master \ rasnes9x \ cpu.cpp (193): fatal error C1083: Unable to open file include: 'RA_Interface.h': No such file or directory
Cpp \ raemus-master \ raasus-master \ rasnes9x \ win32 \ wsnes9x.cpp (252): fatal error C1083: Unable to open file include: 'RA_Interface.h' : No such file or directory
3> Ready compilation project "snes9xw.vcxproj" - FAIL.
========== Compile: 2 successful, 1 failed, 0 refreshed, 0 ignored ==========

**Comment by Jamiras** [comment] 2018-11-16 15:05
> Unable to open file include: 'RA_Interface.h' : No such file or directory
You need to update the submodules. From a command prompt in the RAEmus base directory:
```
git submodule update --init --recursive
```

**Comment by Jamiras** [comment] 2018-11-16 15:06
You might not be able to compile this using the "Download" link. The build process expects `git` to be available:
```
3> fatal: not a git repository (or any of the parent directories): .git
```

**Comment by SyrianBallaS** [comment] 2018-11-16 23:14
You're normally supposed to clone your own fork to make it a hit repo.

**Comment by Jamiras** [comment] 2018-11-30 17:07
Assuming this is caused by downloading the code instead of cloning the repository and its submodules. Closing.

**Closed by Jamiras** 2018-11-30 17:07 UTC
